Repository AndreasReitberger/KlipperRestApiSharp, pull requests merged in 2024-11, with the labels that each got.

#136 Added job interruption status
  src/MoonrakerSharpWebApi/Enums/KlipperJobStates.cs
Labels: enhancement, t/housekeeping ♻︎

#140 Added tests for `Auth` without `ApiKey`
  src/MoonrakerSharpWebApi.SQLite/MoonrakerSharpWebApi.SQLite.csproj
  src/MoonrakerSharpWebApi.Test/MoonrakerSharpWebApi.Test.cs
  src/MoonrakerSharpWebApi.Test/SecretAppSetting.cs
  src/MoonrakerSharpWebApi/MoonrakerClient.Auth.cs
  src/MoonrakerSharpWebApi/MoonrakerClient.Files.cs
  src/MoonrakerSharpWebApi/MoonrakerClient.cs
  src/MoonrakerSharpWebApi/MoonrakerConnectionBuilder.cs
Labels: bug, authentication

#139 Fixed wrong `Http.Methods`
  src/MoonrakerSharpWebApi/MoonrakerClient.Database.cs
  src/MoonrakerSharpWebApi/MoonrakerClient.Printers.cs
  src/MoonrakerSharpWebApi/MoonrakerClient.WebCam.cs
  src/MoonrakerSharpWebApi/MoonrakerClient.cs
Labels: bug
