Repository AndreasReitberger/KlipperRestApiSharp, pull requests merged in 2024-06, with the labels that each got.

#122 Updated `Core` dependency
  src/MoonrakerSharpWebApi.Test/MoonrakerSharpWebApi.Test.cs
  src/MoonrakerSharpWebApi/Models/Events/KlipperIsPrintingStateChangedEventArgs.cs
  src/MoonrakerSharpWebApi/Models/PrinterStatus/KlipperStatusJob.cs
  src/MoonrakerSharpWebApi/Models/WebSocket/KlipperWebSocketKlipperStatusResult.cs
  src/MoonrakerSharpWebApi/Models/WebSocket/Responses/KlipperWebSocketStateRespone.cs
  src/MoonrakerSharpWebApi/MoonrakerClient.Events.cs
  src/MoonrakerSharpWebApi/MoonrakerClient.Files.cs
  src/MoonrakerSharpWebApi/MoonrakerClient.cs
  src/MoonrakerSharpWebApi/MoonrakerSharpWebApi.csproj
Labels: enhancement, t/housekeeping ♻︎, dependencies

#126 Add missing properties
  src/MoonrakerSharpWebApi/Models/Events/KlipperCurrentPrintImageChangedEventArgs.cs
  src/MoonrakerSharpWebApi/Models/Events/KlipperJobListChangedEventArgs.cs
  src/MoonrakerSharpWebApi/Models/Events/KlipperJsonConvertEventArgs.cs
  src/MoonrakerSharpWebApi/Models/Events/KlipperSessionChangedEventArgs.cs
  src/MoonrakerSharpWebApi/Models/Events/KlipperWebSocketDataEventArgs.cs
  src/MoonrakerSharpWebApi/Models/PrinterStatus/KlipperStatusExtruder.cs
  src/MoonrakerSharpWebApi/Models/PrinterStatus/KlipperStatusHeaterBed.cs
Labels: bug

#128 Added `PackageIcon`
  art/ar_128.png
  common.props
  src/MoonrakerSharpWebApi.sln
  src/MoonrakerSharpWebApi/MoonrakerClient.cs
  src/MoonrakerSharpWebApi/MoonrakerSharpWebApi.csproj
Labels: t/housekeeping ♻︎, nuget

#130 Fixed relative movement in `MoveAxesAsync`
  src/MoonrakerSharpWebApi/MoonrakerClient.cs
Labels: bug

#131 KlipperIdleStates Fixup
  common.props
  src/MoonrakerSharpWebApi/Enums/KlipperIdleStates.cs
Labels: bug
